%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Lesson 14
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function plotPhasorDiagram(phaseDifference)

arguments
    phaseDifference (1,1) double
end

figure('Color','w');

hold on
axis equal
grid on

viscircles([0 0],1,...
    'Color',[0.6 0.6 0.6]);

quiver(0,...
       0,...
       1,...
       0,...
       0,...
       'b',...
       'LineWidth',3);

quiver(0,...
       0,...
       cos(phaseDifference),...
       sin(phaseDifference),...
       0,...
       'r',...
       'LineWidth',3);

legend('Unit Circle',...
       'Antenna 1',...
       'Antenna 2',...
       'Location','best')

title('Spatial Phase Difference')

xlabel('In-Phase')
ylabel('Quadrature')