%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Project : Beamforming From First Principles Using MATLAB
%
% Chapter : 01 Fundamentals of Waves
%
% Lesson 15
% Wave Superposition
%
% File:
% Lesson15_MainSimulation.m
%
% Description:
% Main simulation for Lesson 15.
% This script only orchestrates the educational experiment.
%
% Version : 1.0.0
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear;
clc;
close all;

initializeProjectPaths();

%% Experiment 1
% Equal Amplitude Waves

experiment.name = "Equal Amplitudes";

experiment.wave1 = createWave( ...
    "Amplitude",1,...
    "Frequency",1,...
    "Phase",0,...
    "Velocity",1,...
    "Direction","Right");

experiment.wave2 = createWave( ...
    "Amplitude",1,...
    "Frequency",1,...
    "Phase",0,...
    "Velocity",1,...
    "Direction","Left");

runExperiment(experiment);

%% Experiment 2
% Different Amplitudes

experiment.name = "Different Amplitudes";

experiment.wave1 = createWave( ...
    "Amplitude",1,...
    "Frequency",1,...
    "Phase",0,...
    "Velocity",1,...
    "Direction","Right");

experiment.wave2 = createWave( ...
    "Amplitude",0.5,...
    "Frequency",1,...
    "Phase",0,...
    "Velocity",1,...
    "Direction","Left");

runExperiment(experiment);

%% Experiment 3
% Different Frequencies

experiment.name = "Different Frequencies";

experiment.wave1 = createWave( ...
    "Amplitude",1,...
    "Frequency",1,...
    "Phase",0,...
    "Velocity",1,...
    "Direction","Right");

experiment.wave2 = createWave( ...
    "Amplitude",1,...
    "Frequency",1.5,...
    "Phase",0,...
    "Velocity",1,...
    "Direction","Left");

runExperiment(experiment);

%% Experiment 4
% Different Phases

experiment.name = "Different Phases";

experiment.wave1 = createWave( ...
    "Amplitude",1,...
    "Frequency",1,...
    "Phase",0,...
    "Velocity",1,...
    "Direction","Right");

experiment.wave2 = createWave( ...
    "Amplitude",1,...
    "Frequency",1,...
    "Phase",pi/3,...
    "Velocity",1,...
    "Direction","Left");

runExperiment(experiment);

%% Experiment 5
% Same Direction

experiment.name = "Same Direction";

experiment.wave1 = createWave( ...
    "Amplitude",1,...
    "Frequency",1,...
    "Phase",0,...
    "Velocity",1,...
    "Direction","Right");

experiment.wave2 = createWave( ...
    "Amplitude",1,...
    "Frequency",1,...
    "Phase",pi/4,...
    "Velocity",1,...
    "Direction","Right");

runExperiment(experiment);

%% Experiment 6
% Gaussian Wave Packets

experiment.name = "Gaussian Wave Packets";

experiment.simulationTime = 16;

experiment.wave1 = createWave( ...
    "Type","Gaussian",...
    "Amplitude",1,...
    "Frequency",1,...
    "Phase",0,...
    "Velocity",1,...
    "Direction","Right");

experiment.wave2 = createWave( ...
    "Type","Gaussian",...
    "Amplitude",1,...
    "Frequency",1,...
    "Phase",0,...
    "Velocity",1,...
    "Direction","Left");

runExperiment(experiment);

%% Lesson Summary

displaySummary();