function handles = createPhaseSlider(handles,demo)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Lesson 16: Constructive and Destructive Interference
%
% Function:
% createPhaseSlider
%
% Project:
% Beamforming From First Principles Using MATLAB
%
% Description:
% Creates the phase slider used in the interactive demo.
%
% Inputs:
%   handles    Graphics handles.
%   demo       Demo configuration structure.
%
% Outputs:
%   handles    Updated graphics handles.
%
% Version:
% 1.0.0
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

handles.phaseSlider = uicontrol( ...
    'Style','slider', ...
    'Units','normalized', ...
    'Position',[0.20 0.02 0.60 0.04], ...
    'Min',demo.slider.minimum, ...
    'Max',demo.slider.maximum, ...
    'Value',demo.slider.initial, ...
    'SliderStep',[1/360 10/360], ...
    'Callback',@onSliderChanged);

handles.phaseValue = uicontrol( ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',[0.82 0.02 0.10 0.04], ...
    'String','0°', ...
    'FontSize',11, ...
    'BackgroundColor','white');

end